baseURL = "https://blog.bdm.scot"
languageCode = "en-gb"
title = "The bdm.scot Blog"
theme = "ananke"
SectionPagesMenu = "main"

[params]
  favicon = "favicon.ico"
  site_logo = "/img/bdm-scot-logo.png"
  description = "The blog of a Senior Technical Support Engineer based in Scotland"
  #facebook = ""
  #twitter = "https://twitter.com/GoHugoIO"
  #instagram = ""
  #youtube = ""
  github = "https://github.com/bmccafferty"
  #gitlab = ""
  linkedin = "https://www.linkedin.com/in/bmccafferty"
  #mastodon = ""
  #slack = ""
  #stackoverflow = ""
  #rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  #featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 5
